---
- name:  Install Katello CA
  hosts: all
  tasks:
  - name: install katello-ca rpm
    yum:
      name: '{{ katello_ca_url }}'
      state: present
      disable_gpg_check: yes
  

  - name: Register with activation key
    redhat_subscription:
      state: present
      activationkey: '{{ activationkey }}' 
      org_id: Default_Organization
   


  
