---
- name:  Install Katello CA
  hosts: all
  vars:
    katello_ca_url: http://satellite.homelab.local/pub/katello-ca-consumer-latest.noarch.rpm
    activationkey: mykey
    
  tasks:
  - name: install katello-ca rpm
    yum:
      name: '{{ katello_ca_url }}'
      state: present
      disable_gpg_check: yes
  

  - name: Register with activation key
    redhat_subscription:
      state: present
      activationkey: '{{ activationkey }}' 
      org_id: Default_Organization
   


  
