
---
- name:  Install Katello CA
  hosts: all
  tasks:
  - name: uninstall katello-ca rpm
    yum:
      name: "katello-ca-consumer-latest.noarch"
      state: absent
      disable_gpg_check: yes
  
  - name: clean
    command: subscription-manager clean
      

  - name: Unregister
    redhat_subscription:
      state: absent
