---
- name:  Setup VMs
  hosts: rhel8_64Guest
  tasks:




  - name: Check whether the system is already registered
    command: subscription-manager status
    register: rhsm_status
    ignore_errors: yes
    
  - name: Register to Red Hat's RHN
    redhat_subscription:
      state: present
      username: thtran1002
      password: Ozil@1002
      pool_ids: 8a85f99b7c18bf35017c6d0258c44980
    when: rhsm_status.rc != 0
  
  - name: install required packages
    yum:
      name: 
        - httpd
        - firewalld
      state: present

  - name: Firewall configure
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: true
    loop:
      - 80/tcp
      - 443/tcp

  - name: enable httpd service
    service:
      name: httpd
      state: started
      enabled: true

  - name: enable firewalld service
    service:
      name: firewalld
      state: started
      enabled: true
