---
- name:  Rolling Update
  hosts: rhel8_64Guest
  gather_facts: true
  serial: 1
  
  pre_tasks: 
  - name: disable the server in haproxy
    haproxy: 
      state: disabled
      host: "{{ inventory_hostname }}"
      socket: /var/lib/haproxy/stats
      wait: true
    delegate_to: loadbalancer.homelab.local

  tasks:  
  - name: upgrade required packages
    yum:
      name: "{{ item }}"
      state: latest
    loop: "{{ needed_packages }}"

     
       


  post_tasks: 
  - name: enabled the server in haproxy
    haproxy: 
      state: enabled
      host: "{{ inventory_hostname }}"
      socket: /var/lib/haproxy/stats
      wait: true
    delegate_to: loadbalancer.homelab.local
    