---
- name:  Rolling Update
  hosts: rhel8_64Guest
  gather_facts: true
  serial: 1
  
  pre_tasks: 
  - name: disable the server in haproxy
    haproxy: 
      state: disabled 
      backend: app 
      host: "{{ inventory_hostname }}"
      wait: true
    delegate_to: lb.homelab.local

  tasks:  
  - name: upgrade all security packages
    yum:
      name: '*'
      state: latest


  post_tasks:
  - name: enable the server in haproxy
    haproxy: 
      state: enabled 
      backend: app 
      host: "{{ inventory_hostname }}"
      wait: true
    delegate_to: lb.homelab.local
    