---
- name:  Rolling Update
  hosts: loadbalancer.homelab.local
  gather_facts: true
  
  tasks: 
  - name: disable the server in haproxy
    haproxy: 
      state: disabled
      host: node1
      socket: /var/lib/haproxy/stats
      wait: true
