---
- name:  Rolling Update
  hosts: rhel8_64Guest
  gather_facts: true
  serial: 1
  
  pre_tasks: 
  - name: disable the server in haproxy
    haproxy: 
      state: disabled
      host: node1
      socket: /var/lib/haproxy/stats
      wait: true
      drain: true
    delegate_to: loadbalancer.homelab.local

  tasks:  
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest


  post_tasks: 
  - name: disable the server in haproxy
    haproxy: 
      state: enabled
      host: node1
      socket: /var/lib/haproxy/stats
      wait: true
    delegate_to: loadbalancer.homelab.local
    