---
- name: Deploy web content
  hosts: all
  gather_facts: true
  tasks:
    - name: gather ec2 facts
      ec2_instance_info:
        region: ap-southeast-1
      delegate_to: localhost
      register: ec2

    - name: Copy over the httpd index
      template:
        src: index_aws.jinja2
        dest: /var/www/html/index.html
      notify:
        - restart httpd
      become: true


    - name: Copy over the httpd index
      copy:
        src: index_html_image.gif
        dest: /var/www/html/index_html_image.gif
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - restart httpd
      become: true


  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      become: true
