---
- name:  Clone a virtual machine from Linux template and customize
  hosts: all
  gather_facts: false
  tasks:
  - name: provisioning VM from template
    vmware_guest:
      validate_certs: no
      folder: "{{ vsphere_folder }}"
      datacenter: '{{ vcenter_datacenter }}'
      datastore: '{{ vcenter_datastore }}'
      state: poweredon
      template: '{{ vm_template }}'
      name: "srv01.homelab.local"
      esxi_hostname: '{{ esxi_hostname }}'
    delegate_to: localhost

  - name: wait vmware tools started
    vmware_guest_tools_wait:
      validate_certs: no
      name: "srv01.homelab.local"
      folder: '{{ vsphere_folder }}'
    delegate_to: localhost
    register: facts

