---
- name:  Clone a virtual machine from Linux template and customize
  hosts: srv01.homelab.local
  gather_facts: false
  tasks:
  - name: provisioning VM from template
    vmware_guest:
      validate_certs: no
      datacenter: '{{ vcenter_datacenter }}'
      datastore: '{{ vcenter_datastore }}'
      state: poweredon
      folder: '{{ vsphere_folder }}'
      template: '{{ vm_template }}'
      name: '{{ inventory_hostname }}'
      esxi_hostname: '{{ esxi_hostname }}'
      networks:
      - name: '{{ vsphere_port_group }}'
        ip: 192.168.1.151
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers: 192.168.1.110
      customization:
        dns_servers: 192.168.1.110
    delegate_to: localhost

  - name: wait vmware tools started
    vmware_guest_tools_wait:
      validate_certs: no
      name: '{{ inventory_hostname }}'
      folder: '{{ vsphere_folder }}'
    delegate_to: localhost
    register: facts

  - name: wait ssh port
    wait_for:
      port: 22
      host: '{{ ansible_host }}'
      search_regex: OpenSSH
      delay: 10
      timeout: 180
    delegate_to: localhost
