---
- name:  Config generic VMs
  hosts: all
  gather_facts: false
  tasks:
      
  - name: install required packages
    package:
      name: chrony
      state: present
      
  - name: Copy over the chronyd configuration
    template: 
      src: chrony.jinja2
      dest: /etc/chrony.conf
    notify:
    - restart chronyd
    
  - name: set timezone
    timezone: 
      name: "{{ local_timezone }}"

  handlers:
  - name: restart chronyd
    service: 
      name: chronyd  
      state: restarted
