---
- name:  Config generic VMs
  hosts: all
  gather_facts: false
  tasks:
  - name: install required packages
    package:
      name:
      - chrony
      - policycoreutils-python-utils
      - insights-client
      state: present
 
  - name: Copy over the chronyd configuration
    template: 
      src: chrony.jinja2
      dest: /etc/chrony.conf
    notify:
    - restart chronyd

  - name: Check which hypervisor is used
    command: virt-what
    register: hypervisor   
 
  - name: install the latest version of VMware guess-tools
    yum:
      name: open-vm-tools
      state: latest
    when: hypervisor.stdout == "vmware"

  - name: install the latest version of RHV guess-tools
    yum:
      name: ovirt-guest-agent-common
      state: latest
    when: hypervisor.stdout == "kvm"

  handlers:
  - name: restart chronyd
    service: 
      name: chronyd  
      state: restarted